### ISSUE TITLE
Bug: Importing from litestar.security.jwt cause a circular import

### ISSUE THREAD

**Issue by Kumzy** [litestar-org/litestar#2782]
### Description

Hello,

when upgrading from 2.3.2 to 2.4.0 version of litestar.

I got a message saying depreciation warning about the import of `litestar.contrib.jwt` that will be removed in 3.0 and that is deprecated in 2.4.0

### MCVE

```python
from litestar.security.jwt import OAuth2Login
```

### Steps to reproduce

```bash
1. Just import `litestar.security.jwt`
2. See error
```

### Logs

```bash
ImportError: cannot import name 'BaseJWTAuth' from partially initialized module 'litestar.security.jwt.auth' (most likely due to a circular import)
```

### Litestar Version

2.4.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2782">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2782/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2782/pledge.svg">
</picture>
</a>
