### PR TITLE
fix: remove imports from `contrib.jwt` from `security.jwt`.

### LINKED ISSUE #2782: Bug: Importing from litestar.security.jwt cause a circular import
### Description

Hello,

when upgrading from 2.3.2 to 2.4.0 version of litestar.

I got a message saying depreciation warning about the import of `litestar.contrib.jwt` that will be removed in 3.0 and that is deprecated in 2.4.0

### URL to code causing the issue

_No response_

### MCVE

```python
from litestar.security.jwt import OAuth2Login
```

### Steps to reproduce

```bash
1. Just import `litestar.security.jwt`
2. See error
```

### Screenshots

_No response_

### Logs

```bash
ImportError: cannot import name 'BaseJWTAuth' from partially initialized module 'litestar.security.jwt.auth' (most likely due to a circular import)
```

### Litestar Version

2.4.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2782">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2782/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by peterschutt**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

`contrib.jwt` imports from ` security.jwt` which was importing from `contrib.jwt`, and so on.

This PR removes the `contrib` imports from the main lib.

### Close Issue(s)

Closes #2782

### CODE REVIEW

**Review by guacs — APPROVED** [review]

**Comment by peterschutt** [comment]
The reason that this wasn't picked up in tests is because our docs examples still import from `contrib.jwt` and they are tested before our unit tests that import from `security.jwt`.

```python-console
>>> from litestar.security.jwt import OAuth2Login
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/PycharmProjects/litestar/litestar/security/jwt/__init__.py", line 1, in <module>
    from litestar.security.jwt.auth import (
  File "/home/peter/PycharmProjects/litestar/litestar/security/jwt/auth.py", line 7, in <module>
    from litestar.contrib.jwt.jwt_token import Token
  File "/home/peter/PycharmProjects/litestar/litestar/contrib/jwt/__init__.py", line 1, in <module>
    from litestar.contrib.jwt.jwt_auth import (
  File "/home/peter/PycharmProjects/litestar/litestar/contrib/jwt/jwt_auth.py", line 3, in <module>
    from litestar.security.jwt.auth import BaseJWTAuth, JWTAuth, JWTCookieAuth, OAuth2Login, OAuth2PasswordBearerAuth
ImportError: cannot import name 'BaseJWTAuth' from partially initialized module 'litestar.security.jwt.auth' (most likely due to a circular import) (/home/peter/PycharmProjects/litestar/litestar/security/jwt/auth.py)
>>> from litestar.contrib.jwt import OAuth2Login
>>> from litestar.security.jwt import OAuth2Login
```
