### ISSUE TITLE
Bug: debug mode doesn't work

### ISSUE THREAD

**Issue by sfermigier** [litestar-org/litestar#1476]
### Description

I've tried starting the app in debug mode (`STARLITE_DEBUG=true starlite run` or `starlite run --debug`).

I don't get any meaningful messages when the app encounters exceptions, is it should ("debug: If ``True``, app errors rendered as HTML with a stack trace.").

```
 ~/projects/nua4/nua-server  webbits *8 ?2  starlite run --debug                                                                  ✔  9m 23s  17:58:02
Using Starlite app from asgi:app
┌──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Starlite version │ 1.51.9                                                                                               │
│ Debug mode       │ Enabled                                                                                              │
│ CORS             │ Disabled                                                                                             │
│ CSRF             │ Disabled                                                                                             │
│ Request caching  │ Enabled                                                                                              │
│ OpenAPI          │ Enabled path=/schema                                                                                 │
│ Compression      │ Disabled                                                                                             │
│ Template engine  │ JinjaTemplateEngine                                                                                  │
│ Static files     │ path=/static dirs=/Users/fermigier/projects/nua4/nua-server/src/nua_server/static html_mode=Disabled │
└──────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────┘
Starting server process ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO:     Started server process [72033]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

I don't get a traceback in the console, and in the browser I get the same message as in non-debug mode: `{"status_code":500,"detail":"AttributeError(\"'list' object has no attribute 'replace'\")"}`

### Litestar Version

1.51.9

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by Goldziher** [comment]
Please test the issue on our main branch or the last release of `litestar`, version v2.0.0a3. This has been recreated.

**Comment by Goldziher** [comment]
@provinzkraut - can you take alook when you are back?

**Comment by sfermigier** [comment]
Here's a way to reproduce it under starlite.

```
from starlite import Starlite, get


@get("/")
def hello_world() -> dict[str, str]:
    """Keeping the tradition alive with hello world."""
    1 / 0


app = Starlite(route_handlers=[hello_world])
```

**Comment by provinzkraut** [comment]
Confirmed. This is a regression introduced in #1119.

**Comment by provinzkraut** [comment]
Okay so the app will actually be set to debug mode, it's just that we configure logging during app-init, for which we take the `debug` parameter into account.

**Comment by provinzkraut** [comment]
Closed by #1482. @sfermigier this landed in `v2.0.0alpha4`!
